apiVersion: v1
kind: Pod
metadata:
  name: busybox123
  labels:
    kompose.image-pull-policy: Always
spec:
  containers:
    - image: busybox:stable
      command:
        - sleep
        - "3600"
      imagePullPolicy: Always
      name: busybox123
  restartPolicy: Always
